### ISSUE TITLE
Microtasks Feedback

### ISSUE THREAD

**Issue by apoorvaanand1998** [apoorvaanand1998/chaoss-microtasks#1]
This issue is for general feedback on all the microtasks done. I shall also be opening new issues for every microtask, for more specific feedback.

Wherever else I have found feedback already given, those I have noted and have started working on already (For example, [inishchith's](https://github.com/inishchith/chaoss-microtasks/issues) and [sumitskj's](https://github.com/sumitskj/GSOC-Chaoss/issues). Now I understand why everything is up in public :D).  I shall update this repo with the better version of these microtasks soon. Of course, if there's feedback to be given *other* than that which is already given in the other two repos, then I'd be really grateful for them. :)

I also, in haste, decided to link this repository to the [GSoC-interest.md](https://github.com/chaoss/governance/blob/master/GSoC-interest.md) file, hopefully that's not an issue and we weren't supposed to link the "final version" of our microtasks repo there.  

Also, sorry for being super late with the microtasks. :(

**Comment by valeriocos** [comment]
Thank you @apoorvaanand1998 for the effort in working in the microtasks. Overall they look OK and I'm sure you will be able to meet the deadline :)

If you want, you can try to add some content here: https://github.com/apoorvaanand1998/chaoss-microtasks#chaoss-microtasks to recap briefly the work done in each microtask

**Comment by apoorvaanand1998** [comment]
I've worked towards improving Microtask 1 through 8 based on the feedback given @valeriocos, please check it and let me know how I've done. Thank you for all the help. :)

**Comment by apoorvaanand1998** [comment]
Hi @valeriocos, I know this might be too late, but I'd love some feedback on my proposal as well
